/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package decorator;

public class App {

  public static void main(String[] args) {
    Component component = new ConcreteComponent();

    System.out.println(component.operation());

    component = new ConcreteDecoratorA(component);

    System.out.println(component.operation());

    component = new ConcreteDecoratorB(component);

    System.out.println(component.operation());
  }

}
