/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design_pattern;

public class App {
    public static void main(String[] args) {
        Duck duck = new MallardDuck();
        duck.performFly();
        duck.performQuack();
        duck.swim();
        duck.display();

        Duck tubeDuck = new TubeDuck();
        tubeDuck.performFly();
        tubeDuck.performQuack();
        tubeDuck.swim();
        tubeDuck.display();
    }
}
